### ISSUE TITLE
ZygoteManager.killWorker() doesn't call the callback passed in

### ISSUE THREAD

**Issue by yuchenp** [PrairieLearn/zyspawn#5]
After try to call a non-existing file, ZygoteManager.killWorker() doesn't call the callback passed in.

**Comment by cwlowder** [comment]
I figured out the issue, zygote.py has now way of telling its child has died. So, when kill worker is called, the zygote will die, and not respond. Thus, the manager will time out

**Comment by cwlowder** [comment]
Updated to fix issue. Current resolution is to update the signal handler to setCurrent pid of zygote to -1.
